### ISSUE TITLE
Can not install dimod on M1 mac.

### ISSUE THREAD

**Issue by 29rou** [dwavesystems/dimod#1022] opened 2021-10-07 01:13 UTC
**Description**
I can not install dimod on M1 mac.

**Steps To Reproduce**
Old numpy 1.19.4 does not support M1 mac. 
Therefore, You shoud use newer numpy>=1.21.1. 

**Expected Behavior**
"`pip install dimod.`" does not nead build numpy.

**Environment**
 - OS: [macOS 11.6-arm64]
 - Python version: [3.8.2]

**Additional Context**
``` 
(.venv) jij-m1-mac@Jij-M1-MacnoMac-mini arm-tmp % pip install dimod 
Collecting dimod
  Using cached dimod-0.10.7.tar.gz (2.1 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jij-m1-mac/arm-tmp/.venv/bin/python3 /private/var/folders/qk/h2w__39j0k12f9zhg2nf35l00000gn/T/pip-standalone-pip-bxti7w8d/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/qk/h2w__39j0k12f9zhg2nf35l00000gn/T/pip-build-env-0608wyuh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' wheel 'Cython>=0.29.21,<3.0' numpy==1.19.4
       cwd: None
  Complete output (1067 lines):
  Collecting setuptools>=46.4.0
    Using cached setuptools-58.2.0-py3-none-any.whl (946 kB)
  Collecting wheel
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting Cython<3.0,>=0.29.21
    Using cached Cython-0.29.24-py2.py3-none-any.whl (979 kB)
  Collecting numpy==1.19.4
    Using cached numpy-1.19.4.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Building wheels for collected packages: numpy
    Building wheel for numpy (PEP 517): started
    Building wheel for numpy (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/jij-m1-mac/arm-tmp/.venv/bin/python3 /var/folders/qk/h2w__39j0k12f9zhg2nf35l00000gn/T/tmp8nks_hwu build_wheel /var/folders/qk/h2w__39j0k12f9zhg2nf35l00000gn/T/tmpzwja7ibv
         cwd: /private/var/folders/qk/h2w__39j0k12f9zhg2nf35l00000gn/T/pip-install-i72z1aca/numpy_55fa4e7bd3a4469cb1abd6a921a994e9
    Complete output (1042 lines):
    numpy/random/_bounded_integers.pxd.in has not changed
    numpy/random/_philox.pyx has not changed
    numpy/random/_bounded_integers.pyx.in has not changed
    numpy/random/_sfc64.pyx has not changed
    numpy/random/_mt19937.pyx has not changed
    numpy/random/bit_generator.pyx has not changed
    Processing numpy/random/_bounded_integers.pyx
    numpy/random/mtrand.pyx has not changed
    numpy/random/_generator.pyx has not changed
    numpy/random/_pcg64.pyx has not changed
    numpy/random/_common.pyx has not changed
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    blis_info:
      libraries blis not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_info:
      libraries openblas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_blas_info:
      libraries satlas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    accelerate_info:
      libraries accelerate not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
    Library accelerate was not found. Ignoring
      libraries veclib not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
    Library veclib was not found. Ignoring
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_lapack_info:
      libraries openblas not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    openblas_clapack_info:
      libraries openblas,lapack not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    flame_info:
      libraries flame not found in ['/Users/jij-m1-mac/arm-tmp/.venv/lib', '/usr/lib']
      NOT AVAILABLE
  
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries tatlas,tatlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
  
    atlas_3_10_info:
      libraries lapack_atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries satlas,satlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
  
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries ptf77blas,ptcblas,atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
  
    atlas_info:
      libraries lapack_atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries f77blas,cblas,atlas not found in /Users/jij-m1-mac/arm-tmp/.venv/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
  
      FOUND:
        extra_compile_args = ['-faltivec', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
  
    running bdist_wheel
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
    gfortran: warning: this compiler does not support X86 (arch flags ignored)
      adding 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/npymath' to include_dirs.
    None - nothing done with h_files = ['build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/npymath/npy_math_internal.h']
    building library "npysort" sources
      adding 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common' to include_dirs.
    None - nothing done with h_files = ['build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common/npy_sort.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common/npy_partition.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common/npy_binsearch.h']
    building library "npyrandom" sources
    building extension "numpy.core._multiarray_tests" sources
    building extension "numpy.core._multiarray_umath" sources
      adding 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath' to include_dirs.
      adding 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/npymath' to include_dirs.
      adding 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common' to include_dirs.
    numpy.core - nothing done with h_files = ['build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath/funcs.inc', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath/simd.inc', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath/loops.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath/matmul.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/umath/clip.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/npymath/npy_math_internal.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/src/common/templ_common.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/include/numpy/config.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/include/numpy/_numpyconfig.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/include/numpy/__multiarray_api.h', 'build/src.macosx-10.14.6-arm64-3.8/numpy/core/include/numpy/__ufunc_api.h']
    building extension "numpy.core._umath_tests" sources
    building extension "numpy.core._rational_tests" sources
    building extension "numpy.core._struct_ufunc_tests" sources
    building extension "numpy.core._operand_flag_tests" sources
    building extension "numpy.fft._pocketfft_internal" sources
    building extension "numpy.linalg.lapack_lite" sources
    building extension "numpy.linalg._umath_linalg" sources
    building extension "numpy.random._mt19937" sources
    building extension "numpy.random._philox" sources
    building extension "numpy.random._pcg64" sources
    building extension "numpy.random._sfc64" sources
    building extension "numpy.random._common" sources
    building extension "numpy.random.bit_generator" sources
    building extension "numpy.random._generator" sources
    building extension "numpy.random._bounded_integers" sources
    building extension "numpy.random.mtrand" sources
    building data_files sources
    build_src: building npy-pkg config files
    running build_py
```

**Comment by arcondello** [comment] 2021-11-19 18:38
@29rou 0.10.8 has been released with universal wheels. Can you verify that resolves this issue?

**Comment by 29rou** [comment] 2021-11-25 00:36
It's still impossible.
Old numpy 1.19.4 does not support M1 mac.
Therefore, You shoud use newer numpy>=1.21.1.

``` shell
(.venv) %pip install dimod
Collecting dimod
  Using cached dimod-0.10.8-cp39-cp39-macosx_10_9_universal2.whl (5.6 MB)
Requirement already satisfied: numpy!=1.21.0,!=1.21.1,<2.0.0,>=1.17.3 in ./.venv/lib/python3.9/site-packages (from dimod) (1.21.4)
Collecting pyparsing<3.0.0,>=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting dwave-preprocessing<0.4,>=0.3
  Using cached dwave-preprocessing-0.3.1.post0.tar.gz (159 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/nakasho/jij/test/.venv/bin/python3.9 /private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-standalone-pip-p4mzp_nn/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-nzrwk_i_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' 'wheel>=0.30.0' 'Cython>=0.29.21,<3.0' numpy==1.19.4 dimod==0.10.4
       cwd: None
  Complete output (78 lines):
  Collecting setuptools>=46.4.0
    Using cached setuptools-59.2.0-py3-none-any.whl (952 kB)
  Collecting wheel>=0.30.0
    Using cached wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting Cython<3.0,>=0.29.21
    Using cached Cython-0.29.24-py2.py3-none-any.whl (979 kB)
  Collecting numpy==1.19.4
    Using cached numpy-1.19.4-cp39-cp39-macosx_11_0_arm64.whl
  Collecting dimod==0.10.4
    Using cached dimod-0.10.4.tar.gz (2.0 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/nakasho/jij/test/.venv/bin/python3.9 /var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpykhxdi6__in_process.py get_requires_for_build_wheel /var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpe14he37a
         cwd: /private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-install-b64j0x5u/dimod_857a996e119147b7995e2344e471ed85
    Complete output (56 lines):
    Traceback (most recent call last):
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 22, in <module>
        from . import multiarray
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/multiarray.py", line 12, in <module>
        from . import overrides
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/overrides.py", line 7, in <module>
        from numpy.core._multiarray_umath import (
    ImportError: dlopen(/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpykhxdi6__in_process.py", line 363, in <module>
        main()
      File "/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpykhxdi6__in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpykhxdi6__in_process.py", line 130, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
        return self._get_build_requires(
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
        self.run_setup()
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 19, in <module>
        import numpy
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 140, in <module>
        from . import core
      File "/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 48, in <module>
        raise ImportError(msg)
    ImportError:
  
    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
  
    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.
  
    We have compiled some common reasons and troubleshooting tips at:
  
        https://numpy.org/devdocs/user/troubleshooting-importerror.html
  
    Please note and check the following:
  
      * The Python version is: Python3.9 from "/Users/nakasho/jij/test/.venv/bin/python3.9"
      * The NumPy version is: "1.19.4"
  
    and make sure that they are the versions you expect.
    Please carefully study the documentation linked above for further help.
  
    Original error was: dlopen(/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so, 2): no suitable image found.  Did find:
    	/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
    	/private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-qs8j969s/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-darwin.so: mach-o, but wrong architecture
  
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/23/89/ffe4df2a64b433f43acd39599e14338caaf18f87405009cb5751164b8431/dimod-0.10.4.tar.gz#sha256=02d77e98c14a018908aa57c09af73a1dd62c7e4bc37e5d37314bc987d748eb83 (from https://pypi.org/simple/dimod/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/nakasho/jij/test/.venv/bin/python3.9 /var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpykhxdi6__in_process.py get_requires_for_build_wheel /var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/tmpe14he37a Check the logs for full command output.
  ERROR: Could not find a version that satisfies the requirement dimod==0.10.4 (from versions: 0.1.1, 0.3.0, 0.3.1, 0.4.0, 0.5.0.dev1, 0.5.0, 0.6.0.dev1, 0.6.0.dev2, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 0.8.11, 0.8.12, 0.8.13, 0.8.14, 0.8.15, 0.8.16, 0.8.17, 0.8.18, 0.8.19, 0.8.20, 0.8.21, 0.9.0.dev1, 0.9.0.dev2, 0.9.0.dev3, 0.9.0.dev4, 0.9.0.dev5, 0.9.0.dev6, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7.dev0, 0.9.7.dev1, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 0.10.0.dev0, 0.10.0.dev1, 0.10.0.dev2, 0.10.0.dev3, 0.10.0.dev4, 0.10.0.dev5, 0.10.0.dev6, 0.10.0.dev7, 0.10.0.dev8, 0.10.0.dev9, 0.10.0rc1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8)
  ERROR: No matching distribution found for dimod==0.10.4
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2e/2c/f9ff5eb39e4879f510b4f5a804236cbe0e1de3331ece6ffd8b7b4680a898/dwave-preprocessing-0.3.1.post0.tar.gz#sha256=3a6fd6dd360ea4781d09729649cc77c1855738d9cf245d23c75561757d783204 (from https://pypi.org/simple/dwave-preprocessing/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/nakasho/jij/test/.venv/bin/python3.9 /private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-standalone-pip-p4mzp_nn/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/q2/l118jmf92md30jwcnjd38vbw0000gn/T/pip-build-env-nzrwk_i_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=46.4.0' 'wheel>=0.30.0' 'Cython>=0.29.21,<3.0' numpy==1.19.4 dimod==0.10.4 Check the logs for full command output.

**Comment by arcondello** [comment] 2021-11-26 18:34
Right, in this case the error is being caused by dwave-preprocessing, though it should be resolved by https://github.com/dwavesystems/dwave-preprocessing/pull/38

**Comment by arcondello** [comment] 2022-01-19 17:28
Hi @29rou, I think this time we mean it :smile: can you try again?

**Comment by arcondello** [comment] 2022-02-01 17:54
Closing this issue since I believe it has been resolved. Feel free to reopen if I am incorrect!

**Closed by arcondello** 2022-02-01 17:54 UTC
Labels: bug/fix
