### ISSUE TITLE
Support division by a number

### ISSUE THREAD

**Issue by hsadeghidw** [dwavesystems/dimod#1003] opened 2021-09-17 04:57 UTC
**Application**
To be consistent with overloaded operations, I think it should be okay to support division by numbers.

For example, this is possible
```
x = dimod.Binary('x')
print(2 * x)
print(0.5 * x)
```

but this is not supported
```
print(x / 2)
```

It's understandable that the division of two variables is not supported!

**Comment by arcondello** [comment] 2021-09-17 05:11
@rahmani15 beat you to it! Closing as a duplicate of https://github.com/dwavesystems/dimod/issues/984

**Closed by arcondello** 2021-09-17 05:11 UTC
