### ISSUE TITLE
CQM from BQM method

### ISSUE THREAD

**Issue by ACE07-Sev** [dwavesystems/dimod#1155] opened 2022-03-19 19:20 UTC
**Application**
a method to create a CQM from BQM (one that actually functions)

**Proposed Solution**
The CQM is basically a layer of constraints added on top of the BQM, with use of Integer values, hence this method could simply convert the BQM to CQM.

**Comment by arcondello** [comment] 2022-03-20 22:52
I am closing this because there is no [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Closed by arcondello** 2022-03-20 22:52 UTC
